### ISSUE TITLE
Add a timeout for flow execution

### ISSUE THREAD

**Issue by AntoninLeroyEnki** [kestra-io/kestra#1373]
### Feature description

We sometime uses flow to merge / append data to our big query tables in a time dependent manner (sample every hour etc...)
But we found that sometimes there could be flow that takes x100 x1000 the usual run time and still appear as "successful" even if it's technically a success the data temporarily is broken and our data corrupted.

Solution: implement a timeout functionality where the user can setup a time threshold on the overall flow execution to trigger a failure if the threshold is broken.

**Comment by tchiotludo** [comment]
maybe related to this one: https://github.com/kestra-io/kestra/issues/1246

**Comment by Ben8t** [comment]
As a user, I would like to terminate the Execution if the flow is running for longer than a given time (e.g., longer than 5 hours) because it would otherwise consume too much of compute or indicate some sort of anomaly (some process might be stuck or somehow processing more data than usual if it runs for that long).

Timeout vs. SLA
Exposing a timeout on a flow level has some conceptual overlap with SLA https://github.com/kestra-io/kestra/issues/1246

But the problem is also slightly different.

Timeout: When running a flow, the user may want to ensure that it doesn't run for longer than e.g., 1 hour.

SLA: SLA can ensure that the flow should always finish by a specific time, e.g., finish by 9 AM in the morning.

**Comment by tchiotludo** [comment]
maybe related to this https://github.com/kestra-io/kestra/issues/1494! I can be the good moment to move the timeout of a task to the executor, to have a central point for timeout management

**Comment by Ben8t** [comment]
```
id: my_flow
namespace: my_namespace
timeout: PT5M  # if the flow runs for more than 5 minutes then set the execution to FAILED status

tasks:
	- id: query
		type: io.kestra.plugin.gcp.bigquery.Query
		sql: "SELECT * FROM customers"
		timeout: PT5S # task timeout is already existing in actual version
```

**Comment by anna-geller** [comment]
quick note: timeout will be complex to query flow execution time ‒ trigger is more in kestra's mindset

**Comment by anna-geller** [comment]
it will be addressed with a system flow https://github.com/kestra-io/kestra/issues/3350
