### ISSUE TITLE
Plugins release dispatch workflow

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1734]
### Feature description

When deploying a new Kestra version, we also update the plugins.
It would be easier to have a workflow which takes a version and propagates the version upgrade to every plugins to avoid missing a plugin upgrade and provide an easier way to mass-update

**Comment by Skraye** [comment]
Note that we don't release a new plugin for each new version of Kestra, but for each with new features
Meaning that : 
* Upgrade from 0.10 to 0.11 should update the minimal version required (and, with it Plugin version)
* Upgrade from 0.10 to 0.10.1 should not update any plugin

**Comment by loicmathieu** [comment]
This is overly complicated and I think we should simplify stuff.
Even if we need the ability to release a new version of a plugin independently of a new version of Kestra, for each release the best is to publish all plugins even if it's not needed for simplicity purpose (and also because it's easy to miss the need to upgrade ... like for 0.10).
I also wonder if we shouldn't need to move all plugins in a single repo to makes things simpler.

**Comment by anna-geller** [comment]
will be tackled in this cycle in https://github.com/kestra-io/kestra-ee/issues/1513
