### ISSUE TITLE
Administration panel -> Triggers view

### ISSUE THREAD

**Issue by brian-mulier-p** [kestra-io/kestra#1777]
### Feature description

Create a new sidebar menu to be able to display & modify various informations about the Kestra instance.
Add a Triggers view which lists all instance's triggers with the ability to filter by namespace & flow id. Later it will allow unlocking a trigger with some warnings about the risk of duplicate execution.

**Comment by anna-geller** [comment]
is it meant to display flows grouped by Trigger type and namespace? 
- scheduled flows
- flows with webhook triggers + showing the webhook URL/key
- flows with file detection triggers, etc

or is it something else?

**Comment by loicmathieu** [comment]
It may someday but currently it displays all polling triggers with there state and will allow to "unlock" them.
A polling trigger have an evaluation lock and an execution lock and if things goes wild there is no way to unlock them. Moreover this will also allow to understand why a flow didn't started (because the trigger or an execution is still running).

This will be the first pannel in the administration page, we may add others later.

**Comment by anna-geller** [comment]
very cool, thanks for the explanation
