### ISSUE TITLE
Log are scrolling automatically 

### ISSUE THREAD

**Issue by Melkaz** [kestra-io/kestra#1932]
### Expected Behavior

When browsing logs, we often scroll in the logs of a given task.
If you move your cursor and hover another task, the scrolling position of your previous task will be reset.

This complicates navigating across different logs in an execution.

Thanks 🌈

### Environment Information

Kestra: 0.10.0

**Comment by anna-geller** [comment]
are you able to generate a flow to reproduce it? can be something simple like shell script generating logs

**Comment by brian-mulier-p** [comment]
Hello @Melkaz ! Can you please provide more details ? Which tab are you talking about ? Logs, Gantt ?
The only thing I can reproduce which looks to fit your issue is when in Gantt task as you can only open 1 log tab at once which doesn't allow saving cursor position for previous tasks.
However in Logs tab you can freely open multiple tasks ence it keeps a different cursor position for each 🤔 
Can you confirm it's a real pain and there's something I didn't see ?
Ty

**Comment by brian-mulier-p** [comment]
Closing as we said in chat, if you reproduce feel free to reopen with logs from console if you have any :+1:
