### ISSUE TITLE
Improve error messag for unknown property

### ISSUE THREAD

**Issue by loicmathieu** [kestra-io/kestra#2064]
### Feature description

Currently, the following error message is displayed when a flow has an unknown property:

![image](https://github.com/kestra-io/kestra/assets/1819009/b8c58c24-593f-4f56-b232-bf9442479013)

Or when a task has an unknown property:

![image](https://github.com/kestra-io/kestra/assets/1819009/a5960c57-0895-441d-963b-0c7fb27de755)

We should improve the error message to make it more concise and user-friendly.

**Comment by frankzengjj** [comment]
hi I am first time contributor and I gave a try on this case since I think it is a good starting point for me to get to know the codebase. Here are the results of the fix. Lmk what you think and I can send a PR.
<img width="725" alt="Screenshot 2024-05-29 at 10 42 48 PM" src="https://github.com/kestra-io/kestra/assets/20346113/7a6f0b6a-617f-4619-bb49-3990167697e2">
<img width="750" alt="Screenshot 2024-05-29 at 10 42 29 PM" src="https://github.com/kestra-io/kestra/assets/20346113/bdcbd033-531a-46c8-aa9f-b374d60b780d">

**Comment by anna-geller** [comment]
@frankzengjj we would definitely welcome a PR <3 sorry for the delayed response. if you are still up for it, we'd love your contribution

**Comment by frankzengjj** [comment]
hi @anna-geller No worries! My [PR](https://github.com/kestra-io/kestra/pull/3901) for this issue was sent out.

**Comment by loicmathieu** [comment]
Fixed by #3901
