### ISSUE TITLE
EE Namespace Secrets Page always gives unauthorized

### ISSUE THREAD

**Issue by TomCools** [kestra-io/kestra#2315]
### Explain the bug

I am logged in as an administrator. 
When I go to a namespace - secrets page, I get greeted by a toast saying "unauthorized". 
If I try to add a secret, it also gives me "unauthorized".

I have not setup any specific secret store, so I expect it would use the default one (or at least give me an error better than "unauthorized". 

### Environment Information

- Kestra Version: kestra-ee:v0.12.2-full 
- Operating System and Java Version (if not using Kestra Docker image): Dockerized on Ubuntu (running in standalone mode)

**Comment by tchiotludo** [comment]
In fact, micronaut handle 404 as unauthorized response code (due to security constraint, to avoid path scanning). 
When you haven't enable any secrets, the controller route are disabled, and lead to 404 (So unauthorized).
We will disabled the UI if no secret manager is configured. 
Thanks for the report
