### ISSUE TITLE
Scheduled accumulation

### ISSUE THREAD

**Issue by thomas-depierre-ntico** [kestra-io/kestra#3000]
### Describe the issue

In a flow with a scheduled trigger, in the event of any blockage on an execution, the schedules are accumulated. When this blockage is removed, all the unprocessed flows are executed one behind the other. Ex: We have a flow that is triggered every 10 minutes, it remained frozen last night around 4 a.m., since the release this morning, Kesta continues missed executions without the possibility of purging them

### Environment

- Kestra Version: 0.13.3 & 0.14.4

**Comment by anna-geller** [comment]
I believe your issue will be addressed once we allow disabling system backfills https://github.com/kestra-io/kestra/issues/2219 

Once that issue is done, you should be able to configure either on your flow or in a global configuration that you don't want to recover missed schedules and that accumulation of scheduled runs won't happen

**Comment by anna-geller** [comment]
added in 0.15 release -- you can now add a property:

```yaml
recoverMissedSchedules: NONE
```

and this way, the automated backfill will no longer happen

read more here https://kestra.io/plugins/core/triggers/io.kestra.core.models.triggers.types.schedule#recovermissedschedules
