### ISSUE TITLE
The new relative/absolute button on the Executions page is broken on develop

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3051]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/b05fc22f-9cc3-4db2-84d7-580e3a8012a0)

Internal server error: Failed to convert argument [endDateRange] for value [PT0] due to: Text cannot be parsed to a Duration

Also, when we do relative date, there is no need for 2 buttons, only one: "Last 1h", no need for separate relative start date and end date elements

![image](https://github.com/kestra-io/kestra/assets/86264395/3f2db606-cafc-4ff5-9b1a-fc2e100b3cbf)

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by yuri1969** [comment]
That unfortunate error should be fixed by [#3031](https://github.com/kestra-io/kestra/pull/3031).

Note, setting the end of the relative interval to _now_ breaks the start - end usage pattern (inspired by tools like [Graylog](https://hub.docker.com/r/graylog/graylog)). However, it makes the UI less confusing.

**Comment by loicmathieu** [comment]
My issue was a UI bug that apparently you didn't have, I checked and it's because my browser use a slightly bigger font as a default.

@anna-geller I also think that relative is easier to use without an end, this filter header is already crowded with a lot of options and I didn't understood this second select box until I read this issue. We can decide later if we want to remove it or now.

https://github.com/kestra-io/kestra/pull/3031 fixes the Internal Server Error so I'll merge it.

**Comment by anna-geller** [comment]
We should remove it, please. It's confusing. 

Thanks for the update

**Comment by loicmathieu** [comment]
OK, I'll do it on top of @yuri1969's PR

**Comment by loicmathieu** [comment]
Fixed by https://github.com/kestra-io/kestra/pull/3031 and https://github.com/kestra-io/kestra/pull/3053
