### ISSUE TITLE
Consider moving to Postgres 16 or suppressing the warning from JooQ

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3321]
### Feature description

![image](https://github.com/kestra-io/kestra/assets/86264395/0a1c76d8-b78f-4122-b912-8b4fd9be904a)

**Comment by loicmathieu** [comment]
We use the latest tag in our Docker compose which should be Postgres 16.
We use Bitnami in our Helm Chart wich should update frequently, currently it also provide Postgres 16.

So the issue is not at our side but the customer that uses an old version of Postgres, there is nothing we can do except hiding this log if really needed (but I think it's helpful).

**Comment by anna-geller** [comment]
hide the warning to avoid user confusion
