### ISSUE TITLE
Trigger Toggle task and Singer taps + targets (the plugin subgroups of the Singer plugin) are missing an icon

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3669]
### Describe the issue

![image](https://github.com/kestra-io/kestra/assets/86264395/f9b1181a-3cd2-4a7d-a365-7f41145e3a4a)

See https://preview-oss.kestra.io/ui/plugins 

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
In regards to this one - first, I think we've changed something from when this issue was created as this is the current view:

![image](https://github.com/kestra-io/kestra/assets/62475782/4e775664-9ffa-46a3-892f-a997e5c022af)

But the `Triggers` group does not have an icon, that problem is still present, although, I again think that it might be something to be handled on the BE, as this is the response which give the groups listing to the FE

![image](https://github.com/kestra-io/kestra/assets/62475782/0d30b893-eab0-4af5-9294-0a2cc0b236c5)

Triggers missing `icon` property.

**Comment by Skraye** [comment]
close by https://github.com/kestra-io/kestra/commit/925ce686f0e6e73ccc6545e0ae09fcb24f537c55 and https://github.com/kestra-io/plugin-singer/commit/72145d05fc54324cee67da7ce32497b0d02b1d81
