### ISSUE TITLE
Stress-test realtime triggers 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3831]
### Feature description

Ensure that we create only 1 execution per message, even at a high load in a message queue.

**Comment by smunteankestra** [comment]
Made 15k messages that where caught on Kafka Postgres BE seems all good, later will  more details and results
However on Kestra with Kafka BE there where issues, so we tried to Profile it, below I will leave the steps to reproduce load tests
Preconditions: setup Nata for triggering message with following comnad line: "nats pub kestra.trigger "Test Message from NATS TEST 1st message"" (sample of sending one message)
execute_load.sh is a script that runs 15k of the message above I will paste the content in txt form since .sh is not supported 
[execute_load.txt](https://github.com/user-attachments/files/16350203/execute_load.txt)
NOTE: use your local ip address for url instead of "localhost"
Flow 

id: nats
namespace: dev

tasks:
  - id: log
    type: io.kestra.plugin.core.log.Log
    message: "{{ trigger.data }}"
    
triggers:
  - id: watch
    type: io.kestra.plugin.nats.RealtimeTrigger
    url: nats://localhost:4222
    subject: kestra.trigger
    durableId: natsTrigger
    deliverPolicy: All

**Comment by smunteankestra** [comment]
Kestra on postgres result :
Triggered 15k messages all of them delivered as expected
![image](https://github.com/user-attachments/assets/8d286235-dd55-4f28-a1f0-ccb63f9b087f)

![image](https://github.com/user-attachments/assets/5d590a8a-8347-48b6-9876-5e0099a6c2cf)

**Comment by smunteankestra** [comment]
Results on Kafka 
NOt all messages passed
![image](https://github.com/user-attachments/assets/1d4c1dbc-a0bb-46de-9834-c52b704179ff)
![image](https://github.com/user-attachments/assets/a461103f-8a61-4d3a-a6d8-7e6b7fdb525a)
![image](https://github.com/user-attachments/assets/86564742-df19-478f-be38-b6c32783804a)
![image](https://github.com/user-attachments/assets/ec4beb20-1927-401e-918a-b9b841159229)

**Comment by loicmathieu** [comment]
@smunteankestra can you check with less messages on Kafka to be sure this is not a query issue on Elasticsearch/
Something like 1500 messages.

**Comment by smunteankestra** [comment]
Results on performance testing on Kafka with a lower message queue (1500 total messages triggered with the same script as above)
All messages where consumes - no issues except the known issue https://github.com/kestra-io/kestra-ee/issues/1773



![image](https://github.com/user-attachments/assets/1886e3eb-a37b-4746-a45c-5ad969a197c4)
