### ISSUE TITLE
Add a migration script allowing to move the state existing in the State Store to the KV Store

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3852]
In the future, the State Store will no longer be needed after we add the KV Store. KV Store will do the same but more transparently. 

This issue involves adding a **migration script** (or other solution addressing the problem) to facilitate migration from the State Store to the KV Store.  This will make it easier for users to move existing workflows to the new upgraded Singer + Debezium + CloudQuery plugins + optionally allowing moving those to another namespace.

**Comment by brian-mulier-p** [comment]
Considering the choice we've made [here](https://github.com/kestra-io/kestra/pull/4666) to implement it in an old-compatible way, I'd suggest not to provide any script and wait for the migration framework to do all that programmatically because it will be a pain to handle considering we can't use "find by prefix" methods due to namespace being part of the path and this is the only thing related to pattern-finding in most storages

**Comment by brian-mulier-p** [comment]
The choice I've made is that whenever you get the value of a state it will be relocated to KV Store when returning the value so that people can leverage the new KV Store power afterwards

**Comment by anna-geller** [comment]
perfect, makes sense. closing then 👍
