### ISSUE TITLE
Editor can't open files with space in naming

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#3977]
### Describe the issue

in Flows the editor can't open files with space in their naming
Steps:
1 User at flows uploads any file with space in it - screenshot for reference
2 User opens it in editor

Expected: File to be opened
Actual: 500 error mesage

![image](https://github.com/kestra-io/kestra/assets/171780240/d1e53d9e-ca7b-4648-a6be-c38b7a7e5ba5)

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
I would say this is not an issue anymore, as I could not reproduce it with the latest version. Could you re-check @smunteankestra?

**Comment by smunteankestra** [comment]
not reproducing

**Comment by Piyush-r-bhaskar** [comment]
> not reproducing

Add a file - it will let you add but on refresh  you will see `+` for spaces. 
![image](https://github.com/user-attachments/assets/faadb3e2-64df-4780-8252-b5f874c4b667)

Also, Could you try to rename the files/folders with space in name once @smunteankestra & @MilosPaunovic ?

**Comment by MilosPaunovic** [comment]
That is expected behavior - we'd prefer to allow importing the files with spaces in the name and replacing it with `+` character then avoid updates of those files, as, with multiple file update at once, it might be a big job for someone to rename everthing.

I'll close the related PR, but thanks for the efforts on this @Piyush-r-bhaskar! 🚀
