### ISSUE TITLE
Remove the Error logs table from the main Dashboard

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#3984]
I know @loicmathieu is already investigating, just for tracking

![image](https://github.com/kestra-io/kestra/assets/86264395/f2b2e74a-804f-422f-a693-0ecd18a1a3ed)

We can consider removing this visualization if we cannot find a way to fix the load issue

**Comment by loicmathieu** [comment]
I checked and both queries correctly use the indices in both local and the preview env.

On the preview env, there is 22 millions logs in the table, which is huge regarding the sizing of the database so there is little we can do except purging the table or allowing more resources to the database.

The database instance is never purged so there is one year of history in it.

There may be a slight performance improvement doable in one of the two queries thought, I can propose it but it will not any huge improvement in the dashboard as it is really an issue with the database instance that is too small to cope with such a large table.

**Comment by loicmathieu** [comment]
@anna-geller as I said, this is due to a too small database instance / not purged database, I think this visualization provides useful information so I don't think it'll be a good idea to remove it just be we deploy Kestra with a too small database and don't purge our preview instance (I'm working on it).

If you still think we should remove it, we can remove the list of error logs and keep the logs histogram, this is the slowest visualization of the two, this will reduce load on the database (also those calls are made twice, I already opened an issue about it).

**Comment by anna-geller** [comment]
We should remove it because there is a risk some users don't purge the logs and their main dashboard doesn't load then. We will find a smarter way to present that information, a topic for the onsite:)

**Comment by anna-geller** [comment]
superseded by https://github.com/kestra-io/kestra/issues/3822
