### ISSUE TITLE
Some logs can't be seen from the UI but can be downloaded

### ISSUE THREAD

**Issue by daniellavoie** [kestra-io/kestra#3998]
### Describe the issue

Some logs can't be visualized in the UI from the logs and the topology pages. However it can be downloaded and shows that the task does have logs.
![Screenshot 2024-06-11 at 11 16 45 AM](https://github.com/kestra-io/kestra/assets/4403970/5dfb74d3-f236-4fc4-9981-41a248fd3110)
Reproduced on Kestra Cloud: https://us.kestra.cloud/ui/kestra-tech/executions/github/add_to_project/3CjL2gFemSULkwxV8SO2SL/topology

### Environment

- Kestra Version: 0.17.2
- Operating System (OS/Docker/Kubernetes): N/A
- Java Version (if you don't run kestra in Docker): N/A

**Comment by MilosPaunovic** [comment]
Hey @daniellavoie,

I've been looking at this issue and can't really reproduce it (link to execution is not working anymore).

It is possible that this has been sorted out in the meantime - could you give it another test and check out - and if you are able to reproduce, I'll fix it, otherwise, we can close.
