### ISSUE TITLE
[UI] Allow importing multiple files and folders in the Namespace Files editor

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4123]
### Feature description

Currently, you can import a single file or a single folder. It would be great to allow selecting multiple files and folders to import.

![image](https://github.com/kestra-io/kestra/assets/86264395/790208c6-3a54-41a1-9b7f-ecd7e5285d2b)

**Comment by MilosPaunovic** [comment]
@anna-geller I've pushed a change and now we can import multiple files at once, but, for multiple folders, as most browsers do not support this functionality directly, we would need to create a workaround which will take a significant amount of time.

What do you say we close this issue as completed for now, with multiple file import ability, and, if there turns out to be a real need for folders, re-open it?
