### ISSUE TITLE
Page not found when opening some files in the Editor 

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#4293]
### Describe the issue

See: https://share.descript.com/view/wFMJ5X1R709

@MilosPaunovic we can treat those more exotic type formats as those were regular .txt files

### Environment

- Kestra Version: develop
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Quick note on this:

Those `[filename].undefined` occurencies were happening because we were (at first) allowing save of the file without an extension, and upon retrieval of said files, tree wasn't handling them in an expected manner.

I've pushed a fix which will handle that for all of the existing files, but it will not happen anymore on newly created ones, as we now require extension on creation.

**Comment by anna-geller** [comment]
Some files have no extension though, like a Dockerfile or a LICENSE file or .gitignore. Can you verify that we support those files after the fix? Perhaps open a follow up issue if easier

**Comment by MilosPaunovic** [comment]
> Some files have no extension though, like a Dockerfile or a LICENSE file or .gitignore. Can you verify that we support those files after the fix? Perhaps open a follow up issue if easier

This was a great point @anna-geller!

I've amended the system in such a way that now we can support those kinds of files as well (we weren't up until now, but it did not give us any headaches so far), and by doing so, I've uncovered a few more inconsistencies which I've handled in the mentioned PR from above.
