### ISSUE TITLE
UI caching on the server

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#4339]
### Issue description

There seems to be a caching mechanism of some sort on the servers where we deploy our preview versions (both OSS and EE).

When the `Main` workflow successfully finished it's work, deployed frontend is not accessible for some time after that, due to (currently) unknown reasons.

It is possible that Google (or the platform we're using for deployment) is adding some sort of default cache, and that is the thing preventing new UI being visible momentarily after the successful deployment.

**Comment by brian-mulier-p** [comment]
There's no such mechanism afaik. The delay you're experiencing is probably because of the rollout not being synchronous (the rollout is launched at the end of the Main flow but it doesn't wait for all pods to be rolled out before going ending successfully).

In my previous experience we managed to link the deployment (aka pod rollout) to a github deployment to get a notification when the rollout is actually performed but it's a pain to set this up. Another thing could be to perform a synchronous rollout however it's adding some more overhead over github runners so I don't think there's a good solution for now...

**Comment by MilosPaunovic** [comment]
As per comment above, we can close this one.
