### ISSUE TITLE
Blueprint YAML not displaying

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4403]
### Describe the issue

Blueprint ID 223 for example:

![Screenshot 2024-07-23 at 16 07 57](https://github.com/user-attachments/assets/36e36391-8bf2-47fe-9e0d-c238bab00551)

Should look like:
![Screenshot 2024-07-23 at 16 08 49](https://github.com/user-attachments/assets/27615f75-225a-4ca8-a814-0f71621a6b20)

### Environment

- Kestra Version: 0.18 Snapshot
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by MilosPaunovic** [comment]
Hey @wrussell1999, we've had a couple of changes regarding blueprints in the past couple of weeks and this issue seems like a duplicate of https://github.com/kestra-io/kestra/issues/4443, which was fixed by https://github.com/kestra-io/kestra/pull/4444.

It does seem to be behaving as expected, so if you could double check it and close if it's alright, or ping me to take another look if necessary.

**Comment by wrussell1999** [comment]
Working on 0.19 Snapshot on my end so closing this issue.

![Screenshot 2024-08-27 at 13 32 35](https://github.com/user-attachments/assets/74f3d84f-9518-4f71-a369-b48c77f69c0d)
