### ISSUE TITLE
QA combination of task runners and worker groups together

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/kestra#4441]
### Issue description

You should be able to set up a task runner and a worker group at the same time! This can lead to some interesting patterns where you could even have your kestra instance running on a single VM and your worker (associated with a worker group) running on K8s and using K8s task runner would then spin up pods on that K8s cluster

It needs to be thoroughly validated whether a combination of task runners and worker groups works as expected e.g. process task runner spinning up local processes on a designated worker

**Comment by anna-geller** [comment]
1. Migration guide: https://develop.kestra.io/docs/migration-guide/0.18.0/runners
2. Added note about the deprecation of runner property: https://develop.kestra.io/docs/developer-guide/scripts/runners (see deprecated since 0.18)
3. Added note about worker groups: https://github.com/kestra-io/docs/commit/a880877c9d9c8a177c408d2c15897fdcd31085d5
