### ISSUE TITLE
First load of Topology view briefly shows failure before displaying

### ISSUE THREAD

**Issue by nicoallgood** [kestra-io/kestra#4799]
When viewing an _Execution_, the first load of the Topology view briefly displays the following error before displaying correctly.

`An issue occurred while generating the graph which prevents the topology to be displayed.`

The issue can easily be seen on Cloud: [link](https://us.kestra.cloud/ui/demo/executions/shiny_rocks/slack_failure_alert/bTg6GZRtIis1oSJbZ0RcZ) .

![error_on_load](https://github.com/user-attachments/assets/c03e192a-131a-4fae-953b-71f88a493aa0)

Note: after this initial failure, further navigation on Topology views (for any execution) works correctly 👌  However if you force reload the entire app with cmd-R , the next first Topology of an execution will briefly fail similarly

### Environment

- Kestra Version: v0.18.3 ; reproduced too on  0.19.0-SNAPSHOT `c32f5a5`
- Operating System (OS/Docker/Kubernetes): Docker

**Comment by shivanshsharma13** [comment]
### Hi, Greetings to all! 

I checked the code and found that the warning message appears briefly for a moment because the component initially renders before the required data `execution` and `flowGraph` is loaded. When the component first mounted it was undefined and the control lands on `v-else` part, which is a warning message. Once the data loads, the component updates to show the graphs as expected.

I can try fixing the issue

**Comment by MilosPaunovic** [comment]
Great job here @shivanshsharma13! 🚀
