### ISSUE TITLE
Adjust our markdown logs rendering to avoid Python/YAML comments being rendered as markdown H1 (we can keep rendering only for links)

### ISSUE THREAD

**Issue by MilosPaunovic** [kestra-io/kestra#4834]
### Issue description

Sometimes there are logs which look like this:

![image](https://github.com/user-attachments/assets/7830a437-4f6a-4af5-968a-483b9422a6c1)

Probelm here is that we're rendering the log content as markdown, and in the example above the log message is `message: "# Hello World! 🚀"` which in markdown tranlsates to `H1` heading (resulting in big text as we see in the attached image).

As Anna pointed out, it is usual in some programming languages that comments start with `#` character. The question now is for @Ben8t on how to we want to handle this one - if we want to support full markdown log messages, I don't think there is a proper way of determining what is a code comment and what is `MD` heading. Any ideas on this topic?

Relates to https://github.com/kestra-io/kestra/issues/4776.

Alsom related: https://github.com/kestra-io/kestra-ee/issues/1409

**Comment by Ben8t** [comment]
The only use case I can see for logs to be rendered is in case of linking to another app: I can imagine some users willing to render `[link](https://google.com)` as a proper link... But this is edgy, and usually people would render this kind of string in their notification system (slack, email, etc.) or otherwise keeping the link raw.

 👉 **So let's keep them raw by default for now (no markdown rendering)**. If we get reports asking for rendering in the future, one solution would be to add a flag `renderMarkdown: true | false`
