### ISSUE TITLE
[UI] Concurrency allows negative values in the low-code editor

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#4904]
### Describe the issue

Edit flow - add concurency with negative values- it allows to be saved
https://github.com/user-attachments/assets/9000f400-cad2-4a30-9705-2149836e7cc1

### Environment

- Kestra Version: develop
- Operating System (Docker):

**Comment by loicmathieu** [comment]
Validation will fail so the flow could not be saved.

This is a UI only issue in the low code editor, the "number picker" must take into account the min/max from the JSON schema.
Another solution would be to validate the flow when saving the low code editor changes.

**Comment by mounikaperi** [comment]
@MilosPaunovic @smunteankestra 
I would like to work on this issue. Please do assign it to me if no-one is working on it

**Comment by MilosPaunovic** [comment]
@mounikaperi any progress on this?

**Comment by mounikaperi** [comment]
@MilosPaunovic I will give the PR in sometime. Sorry for the delay

**Comment by MilosPaunovic** [comment]
No worries, just checking the status, we definitely appreciate your efforts! 🚀

**Comment by mounikaperi** [comment]
@MilosPaunovic 
Please find my analysis

-> Concurrency limit allows negative value to be entered and also decremented via Minus of ElementPlus
-> Once user either decrements it or enters it in UI, we are dispatching it to io.kestra.core.models.flows.Concurrency.java class where in this java class is checking that the limit should be positive and not null via jakarta constraint validators
-> However, the errors aren't being communicated back to the MetadataEditor.vue component, making us loose the errors and proceed on saving the metadata
-> We might have to come up with ConcurrencyValidator which would validate the exceptions add it as annotation in our Concurrency.java class and send it back to our vue component
-> If the errors are null then we can allow it to save else we might have to show the error below the limit field to the user.

Can you please check if this approach looks fine to you or any other way we can tackle this issue?

**Comment by MilosPaunovic** [comment]
Potentially @Skraye could give you his input on the questions?

**Comment by Skraye** [comment]
As Loic explain, this is a UI only issue

The `metadataEditor` does not send anything to the backend, but only modify the YAML. If you then check the validation executed on the backend, we prevent to save the flow due to wrong concurrency limit set : 
![image](https://github.com/user-attachments/assets/33d39bb9-5e2b-4175-b7ed-0b46b8e64826)

The two solution are the one Loic mention :
> This is a UI only issue in the low code editor, the "number picker" must take into account the min/max from the JSON schema.
Another solution would be to validate the flow when saving the low code editor changes.

1. So we either need to use the flow schema in the metadata editor to add min & max on your number component

2. or apply the modification, validate the string, and if there is any error on the metadata prevent saving them

I would go for the first solution, as we already have the information, its wont make more API call that we already do, and is the one that need the less work, also I think it would be tricky to catch error from the metadata and from the flow itself

**Comment by mounikaperi** [comment]
Sure Thank you @Skraye for the inputs
@MilosPaunovic I will see how we can have the UI only changes done
If any blockers i see will let you know

**Comment by mounikaperi** [comment]
@MilosPaunovic Please review https://github.com/kestra-io/kestra/pull/5500
