### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by priamai** [kestra-io/kestra#505]
### Feature description

Add support for MQTT pub/sub.

**Comment by tchiotludo** [comment]
Hi @priamai 

It's on internal roadmap. 

To help us, can you describe your use case : 
- a plugins to consume or to produce ? 
- what kind of mqtt servers ? activemq, rabbitmq, others ? 

Thanks

**Comment by priamai** [comment]
Hello,
that is great news!
My personal priorities:
- Consume first, produce later
- MQTT version 3.1.1 (MQTT plain and over TLS)
- Eclipse Mosquitto 
- RabbitMQ with plugin of MQTT 3.1.1

**Comment by tchiotludo** [comment]
Thanks for the details.
Since we don't have any pub / sub plugins with Consumer for now, we need some advice from consumers on how do you see that plugins for the consume part.
What do you expect of about the consume : 
- Have an execution for every message (one message will create 1 new execution, and for next task, all we be processed one by one) 
- Have an execution for a batch of message (we will consume till the end of the queue in one execution, in order to batch process, for example, consume the whole queue not consumed, and pass the output to jdbc task for saving on a database) 

The batch is for now my preference since kestra is better handle large volume but I would like to have your opinion. 

To help us on the design, can you explain the kind of dataflow you are waiting to deal ?

**Comment by priamai** [comment]
Hello,
yes my typical use case is an ETL process where I consume messages from an MQTT topic, process them atomically and then load them into a database for example TimescaleDB.
I understand why you prefer batch but this will make the MQTT plugin less appealing because users like me that works on sensor networks do need a processing guarantee.
Why not Kafka? Well a lot of sensor networks are built around MQTT which is a lightweight library for IOT (there is even a lighter version but let's ignore that for now).
Hope it helps!

**Comment by tchiotludo** [comment]
Ok perfect, thanks for clarification :+1: 
I think I will go to default to batch with 2 options:  
```yaml
   maxMessages: 1 
   maxDuration: PT15S
```
That will allow to control, maxMessage or maxDuration (after 15 sec, send the batch) or both that will allow you to use single message consume for every executions.

**Comment by priamai** [comment]
Fantastic when is ready I will test it!

**Comment by tchiotludo** [comment]
Great, in a meantime, If you have java developer, create a plugin is [really easy](https://kestra.io/docs/plugin-developer-guide/), contributions are really appreciate :+1:

**Comment by tchiotludo** [comment]
@priamai: first release of mqtt plugins is [here](https://kestra.io/plugins/plugin-mqtt/). 
Since I'm not a user of mqtt, tell what do you think of the first implementation, thanks :+1:

**Comment by priamai** [comment]
Fantastic I will test it asap.
