### ISSUE TITLE
New Log navigation don't work on temporal view 

### ISSUE THREAD

**Issue by tchiotludo** [kestra-io/kestra#5215]
[Screencast_20240930_095540.webm](https://github.com/user-attachments/assets/48ea5295-28b6-40b5-ab9d-05a26543e271)

**Comment by MilosPaunovic** [comment]
@Skraye Maybe you'll know what is the problem here without that much investigation? If not, I'll handle it.

**Comment by Skraye** [comment]
@brian-mulier-p did the navigation log, he will probably knows

**Comment by MilosPaunovic** [comment]
Ahh, my bad, that was the initial aim. Thanks for pointing in the proper direction.

**Comment by brian-mulier-p** [comment]
I didn't even know about temporal view :clown_face: So I didn't manage anything about that

**Comment by brian-mulier-p** [comment]
Basically it's a matter of indexing everything by level upon raw logs fetch and putting it into [this variable](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/executions/Logs.vue#L69) and after a matter of scrolling :+1:

**Comment by brian-mulier-p** [comment]
You can give it a try if you want otherwise I'll tackle it.

Basically there is 1 var to keep all logs by level, 1 var to hold cursor idx. You need to populate logs by level and handle click to populate the cursor idx (maybe the display is not done at this level because it's done in TaskRunDetails I think) I'm not sure about that latter part

**Comment by sachinks07** [comment]
Can I work on this issue. Thanks!

**Comment by MilosPaunovic** [comment]
@sachinks07 Absolutely! 🚀

**Comment by brian-mulier-p** [comment]
I think this one can be hard considering the complexity of the log handling view so if you struggle @sachinks07 feel free to go for another one :+1:

**Comment by sachinks07** [comment]
Sure, actually last week I went through the code for this and found the implementation (mapping) part interesting. Will give my best and will comment here if I can't come up with the solution.

**Comment by sachinks07** [comment]
Update: Understood the log navigation flow for default view. Will start implementation for temporal view

**Comment by sachinks07** [comment]
Update: I have implemented the log navigation for the temporal view, embedded in an el-scrollbar, and it's working correctly (video of the working flow is attached below). However, since the application uses a dynamic scroller, I'm encountering issues embedding the log view with it. I'll try embedding it in the dynamic scroller and then raise the PR.


https://github.com/user-attachments/assets/75d23c8a-a93c-43e4-8403-edd3911ac387
