### ISSUE TITLE
Issue with package-lock.json Causing Module Resolution Error in Develop Branch

### ISSUE THREAD

**Issue by mithindev** [kestra-io/kestra#5466]
### Issue description

**Description**:  
The presence of `package-lock.json` triggers a module resolution error while attempting to resolve the module `@rollup/rollup-darwin-arm64`.

#### Steps to Reproduce:
1. Include `package-lock.json` in the project.
2. Run `npm install`.
3. Attempt to resolve the module `@rollup/rollup-darwin-arm64`.

#### Expected Behavior:
The module should resolve without errors.

#### Observed Behavior:
A module resolution error is thrown.

#### Proposed Solution:
Deleting the `package-lock.json` file and running `npm install` resolves the issue.

**Comment by Denish3436** [comment]
i would like to work on this @mithindev

**Comment by mithindev** [comment]
Hello @Denish3436, 😊

@MilosPaunovic is the maintainer here. You just need to remove the package-lock.json file, or alternatively, update it to align with the package.json file to resolve the issue!

**Comment by MilosPaunovic** [comment]
Hi @mithindev,

I understand the place from which this issue is coming, but it's always a good practice, especially in large, open-source projects like Kestra is, to include that file into version control.

As you've already mentioned, deleting `package-lock.json` and  running `npm i` locally should solve all the issues you're having right now, and we have regular dependency updates every Wednesday, the day after we're pushing the fresh maintenance release, so that is when the both package related files are going to be updated.

**Comment by mithindev** [comment]
Thank you so much, @MilosPaunovic, for taking the time to explain this. Lesson learned, and I truly appreciate your guidance.
