### ISSUE TITLE
KV store - Add filter / lookup function

### ISSUE THREAD

**Issue by KoenWindey** [kestra-io/kestra#5577]
### Feature description

When there are many Key-Value pairs in a KV store, it may be handy to have a filter / lookup function at the top of the table, allowing the user to quickly find the kv-pair he/she is after.

![image](https://github.com/user-attachments/assets/4c7d1b66-d927-4692-890e-311b04ebae4a)

**Comment by shushuburger** [comment]
Hello, I want to work about this issue. Can you give me a chance to contribute on this issue?

**Comment by Skraye** [comment]
Hey @shushuburger , this feature may request front and back changes, are you ok with this ? (VueJS/Java) 

Also, KV Store use the storage, which could be S3, Azure Storage ..
If its okay for you, I'll assign it to you!

**Comment by MilosPaunovic** [comment]
Or maybe we can add a simple UI only filtering at first @Skraye?

**Comment by Skraye** [comment]
It seems that there is no pagination, so yes just go for a UI filter at first!

**Comment by shushuburger** [comment]
Oh then, may I try to contribute about UI first?

**Comment by Skraye** [comment]
You can go for it!

**Comment by shushuburger** [comment]
Should I fork the whole project or create a branch only for this issue? @Skraye

**Comment by Skraye** [comment]
You must do a fork, I dont think you'll have the permission to create a new branch

**Comment by shushuburger** [comment]
Ok, thanks for giving a help.
Can you tell me name of file that I should approach and edit?
There are lots of files and directories, so it is little bit hard to find my destination.
@Skraye

**Comment by MilosPaunovic** [comment]
Name of the file is `kestra/ui/src/components/namespace/NamespaceKV.vue`.

**Comment by shushuburger** [comment]
I'm so sorry to request your help too much.
I made some changes in that file but I failed to find a way to check how did ui changed.

1. I forked this repository to my own public repository "shushuburger/kestra".
2. After that, I ran it to visually see if I could make a few changes to the UI to contribute successfully.

By using these command line
```
docker build -t shushuburger/kestra:custom .
docker run --rm -it -p 8080:8080 shushuburger/kestra:custom server local 
```
I failed to open kestra because of "/usr/local/bin/docker-entrypoint.sh: 5: exec: /app/kestra: not found".

Also, I tried everything that written on this site("https://kestra.io/docs/installation/docker") and Readme.
However, I failed again.

Could you teach me how can I execute my local repository on docker?
Or correct way to execute my local repository.

Sorry for delaying a process of working.
I promise that if I success to execute my local repository, I will do my best and make a good contribution for you.

@Skraye @MilosPaunovic

**Comment by Skraye** [comment]
Hello @shushuburger , we have a guide to start developing the UI only :
https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code

**Comment by shushuburger** [comment]
![image](https://github.com/user-attachments/assets/193f6037-6f0c-411c-bc9d-f73a393f6bb3)

I did everything in this picture except "npm run build".
![image](https://github.com/user-attachments/assets/dfab2f46-03b3-4c56-997e-219734a0edba)
![image](https://github.com/user-attachments/assets/841c1cb2-f0d7-4662-a432-7583ee59eb24)

And this is my result.
Infinite loading is continuing for more than 30 min.
I tried "docker-compose down", "npm install" and "npm run dev" include closing every taps in my laptop and reopen.

Is it because of CORS? But I already did the solution of CORS by making "cli/src/main/resources/application-override.yml"

@Skraye  @MilosPaunovic

**Comment by Skraye** [comment]
The link I sent you does not redirect to this section but the below one, please check again as you're not following the good part.

**Comment by shushuburger** [comment]
I failed "./gradlew build" too many.... So I just try "frontend build" by "npm install" first.
After that I reached my goal to open my local kestra.
Using "npm run dev", but I only can see empty screen like this.

![image](https://github.com/user-attachments/assets/173f5bd4-c6ca-46b4-b0ba-a7e0168b9a4b)

Should I complete connection with backend? (using by "./gradlew build")?
The reason why I think that I should make a connection with backend is I need a data to show some table, category like the picture like this.
If I don't have any data, I can't check "Am I right or wrong?"
Is there anything that I don't recognize?

![image](https://github.com/user-attachments/assets/bb270414-d9de-423f-9a60-d9260d4d9431)


@Skraye

**Comment by MilosPaunovic** [comment]
@shushuburger You need to follow section [Setup to work without building the backend from the source code](https://kestra.io/docs/getting-started/contributing#setup-to-work-without-building-the-backend-from-the-source-code) from the link @Skraye provided. That will run the backend in Docker and give you directions on how to run frontend locally.

**Comment by shushuburger** [comment]
Really appreciated for you help.
I successed to run frontend locally.
I need to put some key-value sets for continuing my work.
But when I click "New key-value", UI doesn't work.
Is it problem of my network?
@MilosPaunovic 

![image](https://github.com/user-attachments/assets/1c3e1c44-9790-486a-b0af-da4746c182db)

**Comment by MilosPaunovic** [comment]
What do you mean by `UI` does not work? Is there any error, what is the behavior?

**Comment by shushuburger** [comment]
This is the behavior.
When I enter "KV Store" Tap, every behavior that I did on UI doesn't work.
Click the button, move to another page, etc.
Moving to another page works when I push "F5" and reload the page.
But "New key-value" doesn't work no matter what I do.

@MilosPaunovic

**Comment by MilosPaunovic** [comment]
Okay, why don't you pick another issue from the [backlog](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and let someone else take this one.

**Comment by sophiakkm** [comment]
I want to work on this issue. Can you assign it to me? @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Yup, go ahead @sophiakkm! 🚀

**Comment by shushuburger** [comment]
Ok, I will find another issue which I can solve.
But I wonder why my UI doesn't work successfully.
Could you tell me the reasons that my build failed?

@MilosPaunovic

**Comment by MilosPaunovic** [comment]
My best guess is that you haven't followed the setup instructions to the point, or, you have something very specific in your environment.

**Comment by shushuburger** [comment]
'''
If you want to work on the frontend without having to install Java and everything to run the Kestra Application, you may only start a Kestra [Docker container](https://docs.docker.com/engine/install/) and connect the frontend to it.

To do so, you can first use the following [docker compose file](https://gist.github.com/Skraye/9eee812cab84af778d222c64b3bf6748).

Save it as docker-compose.yml and run the following command:
$ docker-compose up
This will start Kestra running with H2 as the database. In the above docker compose, we redirected the port 8080 to 8085 and 8081 to 8086. You can change it to any port you want.

Then, enter in the /ui folder, create a file ui/.env.development.local with the content VITE_APP_API_URL=http://localhost:8085 (if you did not use 8085 as the port for Kestra, remember to also change it here).

Finally, you can install the dependencies with npm install and serve the UI with hot reload at http://localhost:5173/ using the command: npm run dev.
'''

I did all of things in that text.
I went to see a code of "docker-compose.yml" and save it.
docker-compose up at "kestra".
I made "ui/.env.development.local" and did "npm install" and "npm run dev" at "kestra/ui".

Finally, I reached the point same as video (which I send to you).

Should I do "Plugin development"? @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Then you seem to have something in your own machine that is interfering with Kestra, and I have no way to know what.

**Comment by shushuburger** [comment]
Ok, thanks for your help.
I really hope to meet you again at different issue.
(plus, I hope to solve my problem and kestra works successfully on my machine.)

@MilosPaunovic

**Comment by sophiakkm** [comment]
I try to contribute about UI first.
 @MilosPaunovic

**Comment by MilosPaunovic** [comment]
Thanks for this @sophiakkm! 🚀

**Comment by sophiakkm** [comment]
I want to try the backend part, too. Can you open a related issue?
@MilosPaunovic

**Comment by MilosPaunovic** [comment]
We're not going to do any BE filtering here, due to the way KV store is implemented.

If you're looking for more issues to contribute, you can always check out [this list](https://github.com/orgs/kestra-io/projects/15/views/1?filterQuery=no%3Aassignee+label%3A%22good+first+issue%22) and take your pick from there @sophiakkm.

**Comment by sophiakkm** [comment]
OK. Thank you. I'll find another issue.
