### ISSUE TITLE
Review Hover color Tab

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#5619]
### Describe the issue

On hover, the text is completely unreadable.

<img width="874" alt="Capture d’écran 2024-10-23 à 12 18 29" src="https://github.com/user-attachments/assets/61fd4cab-3a85-4f7f-adc2-53a09bccf160">

Could you modify this component using the following one:
<img width="476" alt="Capture d’écran 2024-10-23 à 12 25 04" src="https://github.com/user-attachments/assets/522183b7-c361-4ae2-a4b2-90864970f3ae">
<img width="469" alt="Capture d’écran 2024-10-23 à 12 25 50" src="https://github.com/user-attachments/assets/5198b9ed-ea18-4c67-9a09-4232ffb44835">

Thx!

### Environment

- Kestra Version:
- Operating System (OS/Docker/Kubernetes):
- Java Version (if you don't run kestra in Docker):

**Comment by AbdurRahman2004** [comment]
I would like to express my interest in working on the issue regarding the hover color for Tab #5619. If possible, could you assign this task to me?

**Comment by MilosPaunovic** [comment]
Your interest is noted and you may and go ahead and work on this issue.

**Comment by AbdurRahman2004** [comment]
@Nico-Kestra Could you please guide me on how to locate  this form component on the application so that i can review my changes ?

**Comment by MilosPaunovic** [comment]
This particular one is the execution dialog, when you have inputs in it. But the same styling would be for all of the radio button style elements (https://element-plus.org/en-US/component/radio.html#button-style), you might want to do some overall styling for all the elements in question.

**Comment by MilosPaunovic** [comment]
@priyansh-6307 Why don't we wait to see if @AbdurRahman2004 is working on this, if not, you can take over.

**Comment by anna-geller** [comment]
@priyansh-6307 feel free to take this, it doesn't look like @AbdurRahman2004 is working on it

**Comment by priyansh-6307** [comment]
okay

**Comment by priyansh-6307** [comment]
but i am unable to locate this ?

**Comment by priyansh-6307** [comment]
> but i am unable to locate the html and css file?

**Comment by MilosPaunovic** [comment]
What have you tried so far?

**Comment by Manpreets59** [comment]
Hey are you still working on this issue do you need any help.

**Comment by MilosPaunovic** [comment]
Seems like there is no response from @priyansh-6307 on this, so you can take over @Manpreets59.

**Comment by Manpreets59** [comment]
Hi [Team Member's Name],

I'm currently working on the hover readability issue in the component where the text becomes unreadable. To implement the most effective solution, could you provide some additional information?

Design Specifications: Are there any specific color codes or design guidelines for the hover state? For instance, should the border color, background color, or text color follow a specific theme or contrast ratio?

Component Location: Could you point me to the exact file or folder where this component’s code is located, or any documentation if available? This will help me avoid affecting unrelated components.

Testing Environment: Is there a recommended way to test these changes in our development environment, or any specific conditions under which this issue is most visible?

Expected Behavior: Do we have a sample or reference for the intended design? I’ve seen the screenshots, but if there’s a design system or similar component we can match, that would be helpful.

Any additional details on the usage or dependencies of this component would also be appreciated. Thanks for your help!

**Comment by MilosPaunovic** [comment]
What seems to be the problem @Manpreets59?

**Comment by Piyush-r-bhaskar** [comment]
> What seems to be the problem @Manpreets59?

@MilosPaunovic / @anna-geller   any progress on this ? I see multiple reassignments. Can I try this ?

**Comment by anna-geller** [comment]
seems to be mainly about the true/false, the rest seems to be working fine: https://share.descript.com/view/Gm3MBYwKyAL

**Comment by MilosPaunovic** [comment]
Fantastic work @Piyush-r-bhaskar! 🚀
