### ISSUE TITLE
Just curious about choice of language

### ISSUE THREAD

**Issue by nitinthewiz** [kestra-io/kestra#58]
Hi,

I wanted to reach out over email, but your site is under development. I'm curious about one thing - 

Why are most of the orchestration engines I see on GitHub built using Java? This seems to be a common trait among them.

Could you please detail some of the reasons why you chose Java over, say, go or python? Is it just that you are more familiar with the language?

**Comment by tchiotludo** [comment]
Hello, 

Thanks for reaching me.
The choice of java is mostly done by one motivation on my side : multi thread.
Java is (in my opinion) the most suitable choice for multi threaded application.
A workflow engine need to be multi threaded in order to handle multiple concurrent task on the same process, this allow to have a small footprint (memory and CPU) and be able to handle a lot of concurrent task.

Some language can fit, for example go, some not (Python just can't IMO). There is airflow for example thanks is written in Python and just fail in performance point of view, airflow can't handle more than 6/8 tasks with 1 full vcpu and 4go of memory : some details here for composer a hosted version of airflow https://cloud.google.com/blog/products/data-analytics/scale-your-composer-environment-together-your-business

Another reason is the ecosystem of java, there is many libs around to create custom tasks that can fit all the future need (database, cloud lib, ...).

I really think that the java ecosystem is more mature than for example the go ecosystem.

Last reason, Kestra is built with Kafka as backend, and the only implementation that is complete is in Java, Kafka stream only exist on java, and Kestra is built on top of it

**Comment by nitinthewiz** [comment]
Thank you so much for the explanation! I wondered if multithreading is the main reason for all these Java based task engines but clearly there are other considerations as well!
