### ISSUE TITLE
Executions filter still is applied even if user canceled it 

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5875]
### Describe the issue

Step 1 : Add a filter
Step 2 : remove it by pressing the X cross on it
Step 3: Refresh
Expected: filter to be removed
Actual: Filter remains 

https://github.com/user-attachments/assets/73e7d166-3931-4e92-9b86-94f4a8474797

### Environment

- Kestra Version: develop

**Comment by sarthakvijayvargiya** [comment]
Hi @MilosPaunovic  Can i work on this.

**Comment by MilosPaunovic** [comment]
You can, but as this is a part of our new filters overhaul, I'll take over tomorrow if there's no PR submitted by then.

New filters are now shown only on Executions page (that is the name of the component, as well) so you can start there.

**Comment by MilosPaunovic** [comment]
So, I've looked at this, and, as of this moment, it is expected behavior, as the search is being triggered only when we click the search button to the right.

We can update the expected outcome for the filters to be updated every time we remove a tag, like Stefan did here. Is that what we want from the product perspective @Ben8t?

**Comment by Ben8t** [comment]
Yes, I think the expected behavior from Stephan is the good one. Can we apply this to only "remove" action and not "add filter" (seeing the UI blinking every time a user add a filter doesn't sounds right in this case).

FYI, on GitHub Project filter, everything is applied at every change... (which make the UI blink a lot; not very UX friendly IMO, especially on adds)

**Comment by MilosPaunovic** [comment]
Agreed, will make the necessary change.

**Comment by MilosPaunovic** [comment]
Even better, @sarthakvijayvargiya, are you willing to have this as your first contribution, with a bit of help from my side?

You need to edit the `kestra/ui/src/components/filter/KestraFilter.vue` component and add this `router.push({query: encodeParams(current.value)});` to line 269, as part of the `removeItem` method.

Will wait for your PR if you're up for it?

**Comment by Piyush-r-bhaskar** [comment]
Hi @MilosPaunovic 

I would appreciate the opportunity to  open a PR for this if it's fine to proceed now.
& I can't see any Wrapper component here `kestra/ui/src/components/filter/Wrapper.vue`

Thanks

**Comment by MilosPaunovic** [comment]
Hi @Piyush-r-bhaskar, we'd like to save this one for one of the new contributors willing to start their OSS journey, as an easy win for the beginning. You are already our well versed `Kestra` contributor, so we're safe with you approaching more complex topics, if that's alright with you?

Also, there was some refactoring from the time this issue was created, so the component in question is now renamed to `kestra/ui/src/components/filter/KestraFilter.vue` (will change in the initial response, just to avoid confusion).

**Comment by Piyush-r-bhaskar** [comment]
Thank You @MilosPaunovic 😊 

Sure, I would like to work apart from good first issues. Could you please take me to some which I should try ?

Also, If it's fine to go ahead Can I also move with issues open for a long time & unassigned eventually and that one is 🏷️:good_first_issue.

**Comment by MilosPaunovic** [comment]
You can pick whatever you'd like from the backlog (no need anymore for you to just choose only `good first issue` labeled ones), as long as it is not actively assigned to someone @Piyush-r-bhaskar. Just be aware that here in the comment I meant only for this particular issue, you can tackle any other with the `good first issue` label also.

**Comment by anna-geller** [comment]
this was done by Milos and Ludo it seems
