### ISSUE TITLE
Admin user can add user - but still 422 response code is returned

### ISSUE THREAD

**Issue by smunteankestra** [kestra-io/kestra#5880]
### Describe the issue

User can't set a label 
https://github.com/user-attachments/assets/84bcdb41-f076-416f-ae52-0f235d1b2019

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
This might be related to the BE itself - when I try to edit labels from the UI, when there is `system.correlationId` label present, when I pass the entire labels array to the endpoint `/executions/ID/labels`, it returns this error.

![image](https://github.com/user-attachments/assets/6c75c12b-903d-4cd6-a150-e1649ffd0035)

Is that expected behavior @loicmathieu or do we need to change the endpoint for setting labels?

**Comment by anna-geller** [comment]
it seems to be the same as here https://github.com/kestra-io/kestra/issues/5992 -- if not, feel free to reopen and clarify, thanks! 🙏
