### ISSUE TITLE
Layer Docs: Some links cause the left menu to disappear

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6209]
### Describe the issue

Example on terraform section: 

_I click on this link._:

<img width="1784" alt="Capture d’écran 2024-11-29 à 16 19 17" src="https://github.com/user-attachments/assets/523263e9-6650-4650-8ae0-21f794a20a71">

👇

_Left menu disappeared:_

<img width="2038" alt="Capture d’écran 2024-11-29 à 16 18 02" src="https://github.com/user-attachments/assets/7ea69d84-6881-4cbe-a8a2-d6d5f42e0cc1">

### Environment

- Kestra Version: develop

**Comment by MichaScant** [comment]
Hey can I be assigned this issue please?

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @MichaScant! 🚀

**Comment by MichaScant** [comment]
Hey, has this issue already been fixed? I took a look and while the docs are now appearing on the left side, if I try access the same link (kestra_namespace_secret_key), the left hand side menu does not disappear for me

**Comment by MilosPaunovic** [comment]
Maybe @elevatebart can answer this better?

**Comment by elevatebart** [comment]
I think @Nico-Kestra expects the "normal" Left Menu to be there not to be absent.

By normal I mean the Menu with Overview, Flows, Executions. This menu is absent from the docs page.

Unfortunately, the real bug is not that: 
- We should not go to that page at all
- When clicking on this link one should stay inside the docs bar.

I can also update the Layout for Docs to show the Main menu to avoid feeling lost.

**Comment by elevatebart** [comment]
Sorry @MichaScant 
I think this one will require a bit of context to get right.
