### ISSUE TITLE
Change the font size in tables.

### ISSUE THREAD

**Issue by Nico-Kestra** [kestra-io/kestra#6342]
### Describe the issue

**Actual version 16px**
<img width="1779" alt="Capture d’écran 2024-12-06 à 10 34 36" src="https://github.com/user-attachments/assets/bfbf1574-7af3-4802-99f4-b8ccca99989b">

- [x] Change the font size **for 14px**
<img width="1936" alt="Capture d’écran 2024-12-06 à 10 36 00" src="https://github.com/user-attachments/assets/9bd48649-8011-478b-9795-447f51119cde">

### Environment

- Kestra Version: develop

**Comment by meAnkit18** [comment]
May you assign me

**Comment by MilosPaunovic** [comment]
Absolutely @meAnkit18! 🚀

**Comment by tejas2292** [comment]
Is it okay, if I give it a try too?

**Comment by MilosPaunovic** [comment]
Hi @tejas2292, this issue is already assigned to @meAnkit18, may I suggest that you check our [curated list of good first issues](https://go.kestra.io/contributing) to see if there is something you find interesting enough and think you can tackle independently. It can be further filtered by desired labels to narrow down the results (suggesting to filter by either `area/backend` or `area/frontend` ones, based on your preferences).

**Comment by tejas2292** [comment]
Understood @MilosPaunovic, Thank you for your clear insight.

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @meAnkit18! 🚀
