### ISSUE TITLE
The new right sidebar is not included in translations (Open an issue, Get a demo etc)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/kestra#6451]
### Describe the issue

Example for Japanese:
![image](https://github.com/user-attachments/assets/6e7b8f54-5828-4f89-b662-c5b603a184ed)

### Environment

- Kestra Version: develop

**Comment by MilosPaunovic** [comment]
Nope, and that is like that by design (or at least, the current one), see the prompt there https://github.com/kestra-io/kestra/blob/ed264a5389ae3c8fac9fc33fcd3c1fef01cb99da/ui/src/translations/generate_translations.py#L9.

We can change it if necessary @anna-geller.

**Comment by anna-geller** [comment]
what do you mean with the prompt? it doesn't exclude the sidebar 😅 

What I meant is: "Get a demo" or "Open an issue" could be translated, WDYT? seems better that way -- seems like an issue to tackle in translations JSON files, not in the .py script, am I wrong?

**Comment by anna-geller** [comment]
ahh I see - you thought I meant "Flows" -- I should have specified - I meant the NEW RIGHT sidebar. Sorry for the confusion!

**Comment by MilosPaunovic** [comment]
Sorry, my bad, just saw the left sidebar JA/EN combo and thought that's the problem. But you're right, this can be easily done.

If someone from the community want to contribute, only add new string to `en.json` file, we have automation which will handle all other languages.

**Comment by ghost** [comment]
I can take this up!

**Comment by MilosPaunovic** [comment]
Absolutely, go for it @arpitgupta-it! 🚀

**Comment by ghost** [comment]
I see that the context bar already has strings for the new sidebar present in the en.json file. Am I missing some context here? @MilosPaunovic 

![image](https://github.com/user-attachments/assets/5eb943fe-f3a9-4c3b-afc1-57bd427832e8)

**Comment by MilosPaunovic** [comment]
Maybe they just aren't applied to the right component?

**Comment by arpitgupta-it** [comment]
Hi @MilosPaunovic 
It appears that the references to the en.json file for the context bar (e.g., contextBar.(anything)) are correctly implemented. In my observation, the content is being loaded as expected when the language is set to English, which suggests that the data is being fetched properly.

The issue seems to arise when the translation mechanism fails to load the content for other languages. Could you share your thoughts on what might be causing this issue? Is the translation failing?

[ContextInfoBar.vue from L42 to L50](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/ContextInfoBar.vue#L83-L116)

**Comment by rd-99** [comment]
hey @arpitgupta-it , the bug is related to incorrect import of Composition Api (useI18n).
you can correct the bug with importing via `const {t} = useI18n({useScope : "global"})` - [ContextInfoBar.vue](https://github.com/kestra-io/kestra/blob/develop/ui/src/components/ContextInfoBar.vue#L67-L68)
 instead of  `const {t} = useI18n()`.

You can confirm this with changing the language and saving settings(no change till now) -> reload(language changed for right sidebar), since the local useI18n creates it's own copy instead of changing global one.

**Comment by ghost** [comment]
I've opened a PR. Please review!

**Comment by MilosPaunovic** [comment]
Thanks for the contribution @arpitgupta-it! 🚀
